### ISSUE TITLE
Failed prop type: Invalid prop `children`

### ISSUE THREAD

**Issue by Geeza** [mbasso/react-https-redirect#1]
I receive the following warning using react 15.

```
Warning: Failed prop type: Invalid prop `children` of type `object` supplied to `HttpsRedirect`, expected `array`. in HttpsRedirect
```

I believe the correct PropType would be `node` not array.

**Comment by mbasso** [comment]
Hi @Geeza thank you for contributing with this issue and the PR! 👍
