### ISSUE TITLE
Prop to disable redirect

### ISSUE THREAD

**Issue by fabiosantoscode** [mbasso/react-https-redirect#11]
Use case: I'm testing my app locally with charles proxy, and using HTTPS with charles proxy is a bit of a bummer for me.

So I'd like to have a prop, so I can do `disabled={!!process.env.REACT_APP_NO_HTTPS}`

**Comment by mbasso** [comment]
Hi,
sure, I’ll develop and ship a new version as soon as possibile!

**Comment by mbasso** [comment]
Just released `react-https-redirect@1.1.0` 🎉
