### ISSUE TITLE
create-react-app import react-https-redirect could not be found

### ISSUE THREAD

**Issue by michaeldino27** [mbasso/react-https-redirect#12]
I was trying to import this npm package but it keep on saying: Could not find a declaration file for module 'react-https-redirect'.

I am importing it like so, import HttpsRedirect from 'react-https-redirect';
Another weird thing is that, after i deployed it in GAE, the redirection of http to https worked for a while, after 10min or so it didnt work already. until now.

Any help will be much appreciated.

**Comment by mbasso** [comment]
Hi,
I’ll try to reproduce it as soon as I can. Is it just a warning or an error? Might it be related to TypeScript?

**Comment by michaeldino27** [comment]
Hello @mbasso ,

Thanks you for the quick response on this, i am using js in my create-react-app and I'm importing it as the readme file says, and it gives me a warning when when you hover over the import saying "Could not find declaration". i also tried
`const HttpsRedirect = require("react-https-redirect");` but also saying could not find declaration warning.

**Comment by michaeldino27** [comment]
Hi once again,
I did some research, i couldn't use this npm package because it doesn't have the dist folder.
Not so sure if it should have dist folder once installed, currently i did not get any dist folder after trying to install/reinstall this package.

**Comment by michaeldino27** [comment]
Hello I am closing this issue.
After rounds of testing and deploying despite of the warning it worked surprisingly without modifying anything.

**Comment by mbasso** [comment]
@michaeldino27 thank you for the update 😄
Perfect!
