### ISSUE TITLE
Compatible with meteor ?

### ISSUE THREAD

**Issue by ricardolimaui** [mbasso/react-https-redirect#14]
Hello all
It is possible to use it in the meteor and be applied to all app? Any example of that ?

Thank you

**Comment by mbasso** [comment]
Hi,
I've never used meteor before but I think that you can just wrap your main
react component with the one exposed by this library and it should work
fine. Have you same sample code to paste here?

**Comment by mbasso** [comment]
@ricardolimaui, I'll close this due to inactivity. Please feel free to open it again if needed
